import { ExpressionEvaluator } from '@/lib/expression';
import { getCollectionSchema, getScreenRoots, type JsonValue, type MiniAppSpec, type UiNode } from '@/lib/specTypes';

interface Issue { path:string; message:string; }
function seedState(spec:MiniAppSpec):Record<string,JsonValue>{const state={...spec.state};for(const[k,v]of Object.entries(state))if(typeof v==='number'&&v===0)state[k]=1;return state;}

class Simulator{
 private state:Record<string,JsonValue>;private records:{id:string;createdAt:number;collection:string;values:Record<string,JsonValue>}[]=[];readonly issues:Issue[]=[];private currentScreen:string;
 constructor(private readonly spec:MiniAppSpec,private readonly evaluator:ExpressionEvaluator,mode:'fresh'|'filled'='filled'){
  this.state=mode==='fresh'?{...spec.state}:seedState(spec);this.currentScreen=spec.navigation.start??Object.keys(getScreenRoots(spec))[0]??'home';
  if(mode==='filled'&&Object.keys(spec.collections??{}).length){const names=Object.keys(spec.collections??{});for(const collection of names){const schema=getCollectionSchema(spec,collection);const values:Record<string,JsonValue>={};for(const field of schema?.fields??[])values[field.key]=field.kind==='number'?1:field.kind==='boolean'?true:field.kind==='date'?Date.now():field.kind==='image'?'file://sample.jpg':'sample';this.records.push({id:`seed-${collection}`,createdAt:Date.now(),collection,values});}}
 }
 get scope():Record<string,JsonValue>{
  const flattened=this.records.map(r=>({...r.values,id:r.id,createdAt:r.createdAt,collection:r.collection})) as JsonValue[];
  const scope:Record<string,JsonValue>={...this.state,nowMs:Date.now(),recordCount:this.records.length,records:flattened,currentScreen:this.currentScreen,timerRunning:false,timerElapsed:0,timerRemaining:0,timerFinished:false,llmBusy:false,llmError:null};
  for(const name of Object.keys(this.spec.collections??{})){const suffix=name.replace(/[^A-Za-z0-9]+(.)?/g,(_m,ch:string|undefined)=>ch?ch.toUpperCase():'');const cap=suffix.charAt(0).toUpperCase()+suffix.slice(1);scope[`recordCount${cap}`]=this.records.filter(r=>r.collection===name).length;scope[`recordValues${cap}`]=this.recordValues(name);}
  for(const[key,expression]of Object.entries(this.spec.derived??{})){try{scope[key]=this.evaluator.evaluate(expression,scope);}catch(error){this.issues.push({path:`derived.${key}`,message:`expression fails at runtime: ${error instanceof Error?error.message:String(error)}`});scope[key]=null;}}
  return scope;
 }
 private recordValues(collection:string):number[]{const field=getCollectionSchema(this.spec,collection)?.valueField;if(!field)return[];return this.records.filter(r=>r.collection===collection).map(r=>Number(r.values[field]??0));}
 checkDerived():void{const scope=this.scope;for(const key of Object.keys(this.spec.derived??{})){const value=scope[key];if(typeof value==='number'&&!Number.isFinite(value))this.issues.push({path:`derived.${key}`,message:'evaluates to NaN or Infinity with normal input; guard the divisor or fix the formula'});}}
 checkTemplate(source:string,path:string,locals:Record<string,JsonValue>={}):void{if(!source.includes('{{'))return;for(const match of source.matchAll(/\{\{([^}]+)\}\}/g)){const body=match[1],filtered=body.match(/^(.*[^|])\|\s*([A-Za-z]+)\s*$/),expression=(filtered?filtered[1]:body).trim(),filter=filtered?.[2];try{const value=this.evaluator.evaluate(expression,{...this.scope,...locals});if(typeof value==='number'&&!Number.isFinite(value))this.issues.push({path,message:`template {{${expression}}} shows NaN`});if(typeof value==='number'&&!filter&&!Number.isInteger(value))this.issues.push({path,message:`template {{${expression}}} prints a fractional number without a formatting filter`});}catch(error){this.issues.push({path,message:`template {{${expression}}} fails: ${error instanceof Error?error.message:String(error)}`});}}}
 private truthyWhen(raw:JsonValue|undefined,locals:Record<string,JsonValue>):boolean{if(raw===undefined)return true;if(typeof raw!=='string')return Boolean(raw);try{const value=this.evaluator.evaluate(raw,{...this.scope,...locals});return value!==null&&value!==false&&value!==0&&value!=='';}catch(error){this.issues.push({path:'action.when',message:`condition fails: ${error instanceof Error?error.message:String(error)}`});return false;}}
 private resolve(value:JsonValue|undefined,locals:Record<string,JsonValue>):JsonValue{if(typeof value!=='string')return value??null;const single=value.match(/^\{\{([^}|]+)\}\}$/);if(!single)return value;try{return this.evaluator.evaluate(single[1].trim(),{...this.scope,...locals});}catch{return null;}}
 pressButton(node:UiNode,path:string,locals:Record<string,JsonValue>={}):void{
  if(!Array.isArray(node.onPress))return;if(!node.onPress.length){this.issues.push({path,message:'button has an empty onPress and does nothing when tapped'});return;}const before=JSON.stringify({s:this.state,r:this.records,c:this.currentScreen});let observable=false;
  for(const raw of node.onPress as unknown as Record<string,JsonValue>[]){if(!this.truthyWhen(raw.when,locals))continue;const action=String(raw.action??'');switch(action){case'state.set':{const key=String(this.resolve(raw.key,locals)??'');if(key in this.state)this.state[key]=this.resolve(raw.value,locals);break;}case'state.inc':{const key=String(this.resolve(raw.key,locals)??'');if(key in this.state)this.state[key]=Number(this.state[key]??0)+Number(this.resolve(raw.by??1,locals));break;}case'state.toggle':{const key=String(this.resolve(raw.key,locals)??'');if(key in this.state)this.state[key]=!this.state[key];break;}case'state.random':{const key=String(this.resolve(raw.key,locals)??'');if(key in this.state)this.state[key]=raw.chars?'sample':1;break;}case'records.add':{const collection=String(this.resolve(raw.collection,locals)??'');const values:Record<string,JsonValue>={};for(const[k,v]of Object.entries((raw.values??{}) as Record<string,JsonValue>)){const value=this.resolve(v,locals);values[k]=value;const field=getCollectionSchema(this.spec,collection)?.fields.find(x=>x.key===k);if(field?.kind==='number'&&typeof value==='string'&&Number.isNaN(Number(value)))this.issues.push({path:`${path}.records.add`,message:`"${k}" is numeric but receives non-numeric text`});}this.records.unshift({id:`smoke-${this.records.length}`,createdAt:Date.now(),collection,values});break;}case'records.update':{const id=String(this.resolve(raw.id,locals)??'');const collection=String(this.resolve(raw.collection,locals)??'');const row=this.records.find(r=>r.id===id&&r.collection===collection);if(row&&raw.values&&typeof raw.values==='object')for(const[k,v]of Object.entries(raw.values as Record<string,JsonValue>))row.values[k]=this.resolve(v,locals);break;}case'records.remove':{const id=String(this.resolve(raw.id,locals)??'');this.records=this.records.filter(r=>r.id!==id);break;}case'records.clear':{const collection=String(this.resolve(raw.collection,locals)??'');if(collection)this.records=this.records.filter(r=>r.collection!==collection);break;}case'nav.go':{const target=String(this.resolve(raw.screen,locals)??'');if(getScreenRoots(this.spec)[target])this.currentScreen=target;observable=true;break;}case'nav.back':case'nav.home':observable=true;break;default:if(action.startsWith('timer.')||action.startsWith('notify.')||['clipboard.set','share','haptics','toast','camera.capture','llm.ask','image.generate'].includes(action))observable=true;}
  }
  if(JSON.stringify({s:this.state,r:this.records,c:this.currentScreen})===before&&!observable)this.issues.push({path,message:'pressing this button changes nothing — the app will feel broken'});
 }
}

function flattenLocals(alias:string,item:JsonValue,index:number):Record<string,JsonValue>{const locals:Record<string,JsonValue>={[alias]:item,[`${alias}Index`]:index};if(item&&typeof item==='object'&&!Array.isArray(item)){for(const[k,v]of Object.entries(item)){const safe=k.replace(/[^A-Za-z0-9_]/g,'');const cap=safe.charAt(0).toUpperCase()+safe.slice(1);locals[`${alias}${cap}`]=v;}const values=(item as Record<string,JsonValue>).values;if(values&&typeof values==='object'&&!Array.isArray(values))for(const[k,v]of Object.entries(values)){const safe=k.replace(/[^A-Za-z0-9_]/g,'');const cap=safe.charAt(0).toUpperCase()+safe.slice(1);locals[`${alias}${cap}`]=v;}}return locals;}
function walkExpanded(spec:MiniAppSpec,sim:Simulator,node:UiNode,path:string,visit:(node:UiNode,path:string,locals:Record<string,JsonValue>)=>void,locals:Record<string,JsonValue>={},customStack:string[]=[]):void{
 visit(node,path,locals);
 const custom=spec.components?.[node.type];if(custom&&!customStack.includes(node.type)){const props=node.props&&typeof node.props==='object'&&!Array.isArray(node.props)?node.props as Record<string,JsonValue>:{};const next={...locals};for(const prop of custom.props??[]){const raw=props[prop.name]??prop.default??null;if(typeof raw==='string'){const single=raw.match(/^\{\{([^}|]+)\}\}$/);next[prop.name]=single?new ExpressionEvaluator().evaluateSafe(single[1].trim(),{...sim.scope,...locals}):raw;}else next[prop.name]=raw;}walkExpanded(spec,sim,custom.template,`${path}<${node.type}>`,visit,next,[...customStack,node.type]);}
 if(node.type==='Repeat'&&typeof node.source==='string'){const value=new ExpressionEvaluator().evaluateSafe(node.source,{...sim.scope,...locals});const source=Array.isArray(value)&&value.length?value:[{id:'smoke-record',createdAt:Date.now(),collection:String(node.collection??''),values:{amount:1,category:'sample'}}];const alias=typeof node.as==='string'?node.as:'item';source.slice(0,2).forEach((item,index)=>{const repeatLocals={...locals,...flattenLocals(alias,item,index)};if(Array.isArray(node.children))node.children.forEach((child,i)=>walkExpanded(spec,sim,child,`${path}.repeat[${index}].children[${i}]`,visit,repeatLocals,customStack));});return;}
 if(Array.isArray(node.children))node.children.forEach((child,index)=>walkExpanded(spec,sim,child,`${path}.children[${index}]`,visit,locals,customStack));
}
export interface SmokeResult{ok:boolean;issues:string[];}
export function smokeTest(spec:MiniAppSpec):SmokeResult{
 const evaluator=new ExpressionEvaluator(),fresh=new Simulator(spec,evaluator,'fresh'),filled=new Simulator(spec,evaluator,'filled');fresh.checkDerived();filled.checkDerived();const roots=getScreenRoots(spec);
 for(const[screen,root]of Object.entries(roots)){
  walkExpanded(spec,fresh,root,`screens.${screen}`,(node,path,locals)=>{for(const key of['value','label','title','hint']){const raw=node[key];if(typeof raw==='string')fresh.checkTemplate(raw,`${path}.${key} (on first open)`,locals);}},{});
  walkExpanded(spec,filled,root,`screens.${screen}`,(node,path,locals)=>{for(const key of['value','label','title','hint','readout','empty','placeholder']){const raw=node[key];if(typeof raw==='string')filled.checkTemplate(raw,`${path}.${key}`,locals);}for(const key of['visible','disabled','progress','values']){const raw=node[key];if(typeof raw==='string')try{evaluator.compile(raw);}catch(error){filled.issues.push({path:`${path}.${key}`,message:`expression fails: ${error instanceof Error?error.message:String(error)}`});}}if(node.type==='Button')filled.pressButton(node,path,locals);},{});
 }
 if(Object.keys(roots).length>4)filled.issues.push({path:'screens',message:'more than 4 generated screens is outside the production complexity budget'});
 let nodeCount=0;for(const root of Object.values(roots))walkExpanded(spec,filled,root,'density',()=>{nodeCount++;});if(nodeCount>120)filled.issues.push({path:'ui',message:'the app is excessively dense; split or simplify the information architecture'});
 const serialized=JSON.stringify({roots,components:spec.components});const hasInteraction=/"onPress"|"bind"|"Repeat"|"Calendar"|"Sandbox"/.test(serialized);const hasDynamic=/\{\{|"ProgressRing"|"ProgressBar"|"Chart"|"LineChart"|"PieChart"|"List"|"Table"|"Gallery"/.test(serialized);if(!hasInteraction&&!hasDynamic)filled.issues.push({path:'ui',message:'the app has neither meaningful interaction nor dynamic output'});
 const seen=new Set<string>(),issues:string[]=[];for(const issue of[...fresh.issues,...filled.issues]){const line=`${issue.path}: ${issue.message}`;if(seen.has(line))continue;seen.add(line);issues.push(line);if(issues.length>=16)break;}return{ok:!issues.length,issues};
}
